services:
  autosender:
    image: ghcr.io/stufently/avia-search-bot:latest  # Образ из GHCR
    container_name: avia-search
    volumes:
      # Монтируем директории с данными
      - ./tdatas:/app/tdatas
      - ./sessions:/app/sessions
    env_file:
      - .env  # Монтируем .env файл с переменными окружения
    restart: unless-stopped
