# .github/workflows/docker-build.yml
name: Build Docker image

on:
  push:
    branches: [ main ]        # билд только при пуше в main
  workflow_dispatch:          # возможность запустить руками

permissions:
  contents: read
  packages: write             # нужен для push в ghcr.io

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/tgautoreplybot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3   # включаем Buildx

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
